### ISSUE TITLE
more transparent name for function that reads potential from dict

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE1.jl#12]
Using `read_dict`, especially when paired with importing of every symbol into the namespace in the examples, can be opaque to new users.  

What's the rationale for reading ACE potentials from a saved dict being a function called `read_dict()`, rather than something like an obviously named constructor of some relevant class? Maybe this is more of a julia namespace issue in the example I'm using, but I find it incredibly opaque that I do some "using" at the top of the file, and magically a generic looking function like plain `read_dict()` returns an ACE.  

I'd prefer either 
 - a more obvious name, like `read_potential`
or
 - not importing every symbol in the ACE1 namespace, and instead referring to the function as `ACE1.read_dict`

**Comment by cortner** [comment]
this interface function could also analyze the filename, see whether it is zipped or not and do all the little extra legwork.
