### ISSUE TITLE
exporting and converting between formats

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACE1.jl#21]
In my old `ace_fit.jl` executable script I used `ACE.ExportMulti.export_ACE()` to write `yace` format files that can be used by LAMMPS right now. I'm not entirely sure where this capability should live, but it would be nice (for us, not necessarily for the ACE1 developers) if we could just write some julia/ACE1 native format (JSON, I guess), and there was a converter to other formats.

What is the current status of potential file formats and routines to read and write them?

**Comment by cortner** [comment]
there is a native ACE1 format, and the converter script should simply load that and then call that function you cited above. should be a straightforward 1-line script.

**Comment by cortner** [comment]
We decided to move export functionality into ACE1pack, so I'm closing this issue. If it is still a problem it should be re-opened there please.
