### ISSUE TITLE
ACE performance on Si DFT data

### ISSUE THREAD

**Issue by exapde** [ACEsuit/ACE1.jl#24]
Hi!

I used ACE to fit the Silicon DFT data from this paper https://arxiv.org/pdf/1906.08888.pdf. The data can be downloaded from the following Github site https://github.com/materialsvirtuallab/mlearn/tree/master/data. 

The results are really strange because the errors in the energy and forces for the ACE potential is 10 times more than those of the SNAP potential. 

Any help would be appreciated. 

Thanks,
Cuong

**Comment by cortner** [comment]
Thanks for reporting back! Would you be willing to move this to the Discussion rather than an issue? I prefer to keep issues for software development. Or you are also welcome to join us on ACE Slack? What do you prefer?

**Comment by exapde** [comment]
Yes, please move it to Discussion. Thanks,
