### ISSUE TITLE
`create_artifacts.jl` doesn't work as it should?

### ISSUE THREAD

**Issue by gelzinyte** [ACEsuit/ACE1.jl#29]
The way I understand `scripts/create_artifacts.jl` is that it should download the file from the url and add the corresponding hashes to Artifacts.toml so that the same files can be downloaded whenever an artefact is called. The problem currently, I think, is that a tarfile gets downloaded, but then the line

```
tarball_hash = archive_artifact(hash_, joinpath(tarfile))
```

re-compresses the downloaded file and gives a hash not to the original file, but to the tarball. As a result, whenever an artefact is called, the original (non-tarred) file gets downloaded, but its hash doesn't match the hash of the downloaded and archive_artifact-tarred hash.

Instead of using `archive_artifact`, the script should just get and bind the hash of the directly downloaded file, which `ArtifactUtils` does.

You can also see the problem by re-running create_artifacts.jl  - it gives different file-hashes every time.

I think I solved the "make a file with a url into an artefact" issue in ACE1pack, [here](https://github.com/ACEsuit/ACE1pack.jl/blob/fix-artefacts/scripts/generate_artifacts.jl#L9).

**Comment by cortner** [comment]
I'm afraid I have no memory at all of writing this (but I see that I did.) Is this something urgent / important to look into or you just noticed it and reported it?

**Comment by gelzinyte** [comment]
No everything works as is, just making a note for whenever anyone might want to add a new artefact.

**Comment by cortner** [comment]
I just manually generated another artifact following the `Pkg.Artifacts` docs [here](https://pkgdocs.julialang.org/v1/artifacts/#Using-Artifacts) and it worked fine. Maybe I can just get rid of that script entirely?

**Comment by gelzinyte** [comment]
Sure, and if there's ever need for automation that can be done correctly?

**Comment by cortner** [comment]
@gelzinyte  - I'm closing this. If you remember how you created the artifacts, would you be willing to write a short set of instructions in the readme of the `ACEData` ?
