### ISSUE TITLE
Installation issue with IPFitting

### ISSUE THREAD

**Issue by braxtonowens** [ACEsuit/ACE1.jl#33]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/45109437/173915059-9bf893c2-cc37-4f5c-9ee2-dc701ce972ee.png">

Unsure how to continue. Any help would be appreciated. Thanks!  

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04" 
```

**Comment by braxtonowens** [comment]
I tried it on my own machine and got the same result

<img width="584" alt="image" src="https://user-images.githubusercontent.com/45109437/173925723-7bc31125-f539-4720-82bf-34fd0f6e01dd.png">

**Comment by cortner** [comment]
have you tried to run the tutorials? These are just warnings and should not affect your ability to use the codes.

**Comment by cortner** [comment]
For you reference - we are planning to retire IPFitting very soon hence haven't fixed this. I'm not sure why this happens with ACE1pack and we should look into it. Would you be willing to file an issue in the ACE1pack repository?

**Comment by braxtonowens** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/45109437/173926715-9547a40b-f7c6-4bdf-bde2-fcd4d3833039.png">

**Comment by cortner** [comment]
ok this is an unrelated issue I think.

**Comment by cortner** [comment]
I'll reopen if we find out there is a genuine problem.
