### ISSUE TITLE
Cannot Export yace file.

### ISSUE THREAD

**Issue by iamusen** [ACEsuit/ACE1.jl#36]
Hi,
After I update the ACE1.jl, I cannot write out the yace file and got the following notice:
`julia> ACE1.ExportMulti.export_ACE("test",pot)
ERROR: type SArray has no field trans
Stacktrace:
 [1] getproperty
   @ ./Base.jl:42 [inlined]
 [2] export_polypairpot(V2::PolyPairPot{Float64, ACE1.OrthPolys.TransformedPolys{Float64, AgnesiTransform{Float64, Int64}, ACE1.OrthPolys.OrthPolyBasis{Float64}, ACE1.OrthPolys.OneEnvelope}, 2}, reversed_species_dict::Dict{String, Int64})
   @ ACE1.ExportMulti ~/.julia/packages/ACE1/2poLQ/src/export/export_multispecies.jl:85
 [3] export_ACE(fname::String, IP::JuLIP.MLIPs.SumIP{AbstractCalculator})
   @ ACE1.ExportMulti ~/.julia/packages/ACE1/2poLQ/src/export/export_multispecies.jl:42
 [4] top-level scope
   @ REPL[81]:1 `
I supposed that this issue could be solved by updating the 83 line in export_multispecies.jl:
`Pr = V2.basis.J[1]`

**Comment by cortner** [comment]
Hang on for a moment and ignore the comment above!!

**Comment by cortner** [comment]
@casv2 - did we ever implement the LAMMPS export for the agnesi-transform?

**Comment by cortner** [comment]
[This line](https://github.com/ACEsuit/ACE1.jl/blob/2ec72ce7be513a079a4d8200492591935e18c2e1/src/export/export.jl#L37)

indicates to me that we didn't implement the export of the Agnesi transform. 

@casv2 and @WillBaldwin0 can you both confirm this?

**Comment by cortner** [comment]
For the record - we are discussing switching over to splines for all evaluation which would in particular remove this issue. But for now - unless Cas or Will have an idea - I have no solution I'm afraid.

**Comment by iamusen** [comment]
I see. Great thanks.

**Comment by cortner** [comment]
Do you mind telling me who I am "talking" to? Your GitHub details don't show anything Are you in Gabor's group?

**Comment by iamusen** [comment]
Thanks for your kind help. I will organize it tomorrow when I get back to my office.

**Comment by iamusen** [comment]
Hi,
Thx for your warm help.
I've used the scripts [here:](https://github.com/iamusen/ace_toymodel.git) and generated the .yace file.
However, the LAMMPS could not read the .yace file except by resetting the radbasename to "ACE.jl.base".

**Comment by WillBaldwin0** [comment]
Yes this is actually a bug we have not yet fixed - when exporting to yace, lamps expects the typenames to be ACE not ACE1. We'll fix this in an uncommon patch via the ACE1pack package. For now everything should work fine with just changing occurrences of ACE1 to ACE in the file

**Comment by casv2** [comment]
@WillBaldwin0 Let's move that fixed export to ACE1pack and remove it from ACE1.jl?

**Comment by iamusen** [comment]
Great Thanks
