### ISSUE TITLE
0.9.3 breaking change?

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACE1.jl#45]
```
using ACE1
ACE1.PolyTransform(p = 0, r0 = 1)
```
This works for `0.9.2` but fails for `0.9.3` and above. It's causing one of the ACE1pack tests to fail (although I've managed a workaround there, equivalent to changing `r0 = 1` --> `r0 = 1.0`).

If you care to allow this syntax, I think you just need another constructor
```
PolyTransform(; p = 2, r0 = 2.5) = PolyTransform(p, r0)
```
The error:
```
ERROR: LoadError: MethodError: no method matching PolyTransform(::Int64, ::Int64, ::Float64)
Closest candidates are:
  PolyTransform(::TP, ::T, ::T) where {TP, T} at ~/.julia/packages/ACE1/mbVt1/src/polynomials/transforms.jl:51
  PolyTransform(::Any, ::Any) at ~/.julia/packages/ACE1/mbVt1/src/polynomials/transforms.jl:56
Stacktrace:
 [1] PolyTransform(; p::Int64, r0::Int64, a::Float64)
   @ ACE1.Transforms ~/.julia/packages/ACE1/mbVt1/src/polynomials/transforms.jl:57```

**Comment by cortner** [comment]
Strange - I'll fix this if course

**Comment by wcwitt** [comment]
It makes sense once you look at it, but it is a bit of a corner case

**Comment by cortner** [comment]
this is now fixed in `main` and will go into 0.10.2. Do we need to backport it to 0.9?

**Comment by wcwitt** [comment]
Thanks. I don't think the backporting is necessary.

**Comment by cortner** [comment]
Then I'll close this and tag/register a new version
