### ISSUE TITLE
Create committee from IPSuperBasis

### ISSUE THREAD

**Issue by wcwitt** [ACEsuit/ACE1.jl#46]
I'm trying to catch up on all the committee enhancements. Thanks for them!

As best I can tell
```
ACE1.committee_potential(basis, c, co_c)
```
only accepts `basis` of types `PolyPairBasis` and `RPIBasis`. It would be nice/natural if it could also accept a combined `basis` of type `JuLIP.MLIPs.IPSuperBasis`.

Not urgent, as I see from the tests how to achieve the same thing outside of ACE1 for now.

**Comment by cortner** [comment]
You are right - this ought to be fixed.

**Comment by wcwitt** [comment]
This is my current workaround
```
function committee_potential(basis::JuLIP.MLIPs.IPSuperBasis{JuLIP.MLIPs.IPBasis}, C, committee)
    i1 = 1
    com_pots = []
    for b in basis.BB
        i2 = i1 + length(b) - 1
        com_pot = ACE1.committee_potential(b, C[i1:i2], committee[i1:i2,:])
        push!(com_pots, com_pot)
        i1 = i1 + length(b)
    end
    return JuLIP.MLIPs.SumIP(com_pots)
end
```
Seems to work, but not super well tested.

**Comment by cortner** [comment]
this is now on `master` and will be in the next realiease 0.10.2
