### ISSUE TITLE
Obtain matrix of descriptor derivatives w.r.t. atomic coordinates

### ISSUE THREAD

**Issue by VladCarare** [ACEsuit/ACE1.jl#47]
As discussed on Slack, I would like to be able to obtain a matrix of descriptor derivates with respect to atomic coordinates. i.e. a matrix of size Nbasis x 3Natoms *per environment*. 

The furthest I can go so far is doing forces(basis,at), which gives me a Nbasis x 3Natoms matrix *per structure*.

**Comment by cortner** [comment]
closed by #48. We can continue to discuss any remaining issues and usage in that PR.
