### ISSUE TITLE
Update to new AtomsBase compliant JuLIP and tag new version

### ISSUE THREAD

**Issue by tjjarvinen** [ACEsuit/ACE1.jl#70]
JuLIP v0.14.0 has AtomsBase conversion tools that are needed, when implementing interfaces to AtomsBase compliant programs like Molly.

So:
- make ACE1 to depend from JuLIP v0.14 or later
- change ACE1 version to v0.11.5
- tag the new version to  ACEregistry
- (change ACE1 version to v0.11.6-DEV - this is optional but good practice)

After this, I can start working on Molly interface.

**Comment by cortner** [comment]
closed via zoom meeting
