### ISSUE TITLE
ACE1.Export not defined

### ISSUE THREAD

**Issue by joannajzou** [ACEsuit/ACE1.jl#75]
I'm looking to use ACE1.jl to write parameters of an ACE potential to a file (.ace), used as an input to a LAMMPS script.

I try this with the following: 
`basis = get_rpi(rpi_params)`
`IP = JuLIP.MLIPs.combine(basis, coeffs)`
`ACE1.Export.export_ace("parameters.ace", IP)`

However I get the following error: 
`ERROR: UndefVarError: Export not defined`

It appears that ACE1.Export no longer exists in the repo, though it is called on in [scripts/generate_ace_tests.jl](https://github.com/ACEsuit/ACE1.jl/blob/main/scripts/generate_ace_tests.jl). Has the export_ace function been superceded?

**Comment by cortner** [comment]
Hi Joanna - ACE1.jl has become pretty much just a backend to `ACE1pack.jl` - please use that instead. Lammps export should work there, but may require merging of the latest development branch. 

https://github.com/ACEsuit/ACE1pack.jl

CC @wcwitt

**Comment by cortner** [comment]
`ACE1pack.jl` (via `ACE1x.jl` and `ACE1.jl`) also comes with much much better default heuristics for basis construction than `ACE1.jl` does. We hope to clean up the multi-repository and dependency mess in the future.

**Comment by joannajzou** [comment]
That solves the issue for me - I'm able to use the export functions in ACE1pack, and will look to migrate to ACE1pack in my workflow. Thanks for your response!
