### ISSUE TITLE
IPFitting vs ACEfit

### ISSUE THREAD

**Issue by cortner** [ACEsuit/ACE1.jl#8]
Should we continue to work on IPFitting for ACE1, or move all work over to ACEfit - and then of course make sure it is compatible with both ACE1 and ACE ? 

@casv2 I think this is partly for you to think about.

**Comment by casv2** [comment]
I think it would be right to start over in ACEfit. It'll allow us to start over and implement the most important features. Also we can start thinking of adding the distributed fitting protocols, which IPFitting is not really designed to do. I think it's perhaps also natural to move away from IPFitting as I think we've decided to also leave JuLIP behind.

**Comment by cortner** [comment]
I think this is pretty much happening with IPFitting just a stop-gap solution, so I'll close this.
